version: '3.8'

services:
  # Tầng 1: Database & Cache
  redis:
    image: redis:7-alpine
    container_name: techgear-redis
    ports:
      - '6379:6379'

  # Tầng 2: Backend Server
  app:
    build: .
    container_name: techgear-server
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - redis

  # Tầng 3: Đường hầm ra Internet (Ngrok)
  ngrok:
    image: ngrok/ngrok:latest
    container_name: techgear-ngrok
    # ĐÃ SỬA Ở ĐÂY: Viết thành một chuỗi liền và thêm http://
    command: 'http http://app:3000'
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - app # Bắt buộc Backend Server phải chạy trước khi mở cổng ngrok
    ports:
      - '4040:4040'
