services:
  # Tầng 1: Database & Cache
  redis:
    image: redis:7-alpine
    container_name: techgear-redis
    ports:
      - '6379:6379'

  # Tầng 2: Backend Server
  app:
    build: .
    container_name: techgear-server
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis # Docker tự hiểu 'redis' là cái service ở trên
      - REDIS_PORT=6379
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - redis # Bắt Redis phải lên trước rồi App mới lên sau
